version: '3.2'
services:
  springboot:
    build:
      context: ./
      dockerfile: springboot.dockerfile
    image: hedza06/spring-docker
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - spdoc-net

  sp-db:
    build:
      context: ./
      dockerfile: db.dockerfile
    image: hedza06/spring-db
    ports:
        - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/db-data:/var/lib/mysql
      - ./data/db-init:/docker-entrypoint-initdb.d
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - spdoc-net

networks:
  spdoc-net: