spring:
  application:
    name: Spring Boot Caching With Redis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/redis?useUnicode=true&characterEncoding=utf8&useSSL=false
    name:
    username: root
    password: 
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    show_sql: true
    properties:
        hibernate.cache.use_second_level_cache: false
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true
  redis:
    host: localhost
    port: 6379
  jackson:
        serialization:
          write_dates_as_timestamps: false
  cache:
    type: redis

liquibase:
      change-log: classpath:liquibase/master.xml

server:
  port: 8080

debug: true